### ISSUE TITLE
Blockquote won't show title if there is no link

### ISSUE THREAD

**Issue by paskal** [parsiya/Hugo-Shortcodes#7]
Hello, friend!
$subj. Example:

```
{{< blockquote author="Марк Аврелий" title="Наедине с собой" link="http://www.opentextnn.ru/man/?id=518" >}}
Да живи ты хоть три тысячи лет, хоть тридцать тысяч, только помни, что человек никакой другой жизни не теряет, кроме той, которой жив
{{< /blockquote >}}
```

If I remove link, title will go away, which is not good in my opinion - one should be able to quote the book without linking.
By the way, thanks for the plugin again, it's amazing.

**Comment by parsiya** [comment]
Good catch, thanks for letting me know. This was also a problem if I had a title and no link. The title would be an empty link.

I have fixed it and added the test case to the blockquote test file.

```
Quote with title and no link
{{< blockquote author="Author5"  title="Google" >}}
  This is a quote from Author5 and links to https://www.google.com with title "Google."
{{< /blockquote >}}
```
![image](https://user-images.githubusercontent.com/3981231/37746321-0746bbf8-2d50-11e8-8e1e-9a90c7cad305.png)
